DFE-Digital/early-career-framework-register-prototype

app/views/training-provider-signed-in/find-and-add-schools-results.html
Two changes here:
- disable the two buttons when no schools selected
- Make the select all checkbox work
=> Disable button and select all

app/views/training-provider-signed-in/find-and-add-schools-confirm.html, app/views/training-provider-signed-in/find-and-add-schools-results.html
Two things:
- show the correct schools on the confirmation page
- hide the remove button when no schools selected
=> School names

app/views/test-redirect-delete-later/1.html, app/views/test-redirect-delete-later/2.html, app/views/test-redirect-delete-later/3.html, app/views/test-redirect-delete-later/4.html, app/views/test-redirect-delete-later/test.html, lib/utils.js
Some code to enable the use of simple redirect within the prototype as apposed to using the routes file for this. Keeps its simple. Have left an example in for now to illustrate.
=> redirect code added to utils to enable less use of the routing

app/assets/sass/application.scss, app/views/sprint-16/school-signed-in/school-add-participants-to-cohort/cohort-participant-listing.html, app/views/sprint-16/school-signed-in/school-add-participants-to-cohort/details.html
SOme changes to the dashboard and the details page relating to chat with UR
=> Personal details page

app/assets/sass/application.scss, app/views/admin/user-research/dashboard.html, app/views/sprint-16/school-signed-in/school-add-participants-to-cohort/cohort-participant-listing.html, app/views/sprint-16/school-signed-in/school-add-participants-to-cohort/confirm-participant-details.html, app/views/sprint-16/school-signed-in/school-add-participants-to-cohort/enter-email-address.html, app/views/sprint-16/school-signed-in/school-add-participants-to-cohort/enter-personal-details.html, app/views/sprint-16/school-signed-in/school-add-participants-to-cohort/success-participant-added.html
Made another variation on the dashboard - to try and flush out some options for users - see what they are preferring to see - could be a combination of various iterations.
=> third variation on dashboard

app/views/sprint-17/teacher-or-mentors/cip-validation/confirm-qtc-details.html, app/views/sprint-17/teacher-or-mentors/cip-validation/dqt-contact.html, app/views/sprint-17/teacher-or-mentors/cip-validation/name-change-ect.html, app/views/sprint-17/teacher-or-mentors/cip-validation/name-maybe.html, app/views/sprint-17/teacher-or-mentors/cip-validation/name-not-updated.html, app/views/sprint-17/teacher-or-mentors/cip-validation/particpant-email.html, app/views/sprint-17/teacher-or-mentors/cip-validation/qct-ect.html, app/views/sprint-17/teacher-or-mentors/cip-validation/sign-in-check-email-ect.html, app/views/sprint-17/teacher-or-mentors/cip-validation/sign-in-continue-to-account-ect.html, app/views/sprint-17/teacher-or-mentors/cip-validation/trn-ect.html, app/views/sprint-17/teacher-or-mentors/cip-validation/trn-error.html, app/views/sprint-17/teacher-or-mentors/cip-validation/trn-get.html, app/views/sprint-17/teacher-or-mentors/cip-validation/trn-info.html, app/views/sprint-17/teacher-or-mentors/cip-validation/update-name.html
Content updates for https://dfedigital.atlassian.net/browse/CPDRP-621?atlOrigin=eyJpIjoiZDNhYmE2MjEwMGVhNGRlZDk0ODc4ODMxYWE0Y2Q5ZmMiLCJwIjoiaiJ9
=> Validation

app/views/admin/listings.html, app/views/index.html
=> dates updated

app/views/admin/listings.html, app/views/sprint-17/teacher-or-mentors/cip-validation/particpant-email.html
Initial fix for the fallback option.
=> fixed broken page and added ECT as default option

app/views/admin/user-research.html, app/views/admin/user-research/validation.html, app/views/sprint-17/teacher-or-mentors/cip-validation/particpant-email.html, app/views/sprint-17/teacher-or-mentors/cip-validation/start-registration.html
=> Updated heading for the start-registration page

app/views/sprint-17/teacher-or-mentors/cip-validation/dqt-contact.html, app/views/sprint-17/teacher-or-mentors/cip-validation/finish-ect.html, app/views/sprint-17/teacher-or-mentors/cip-validation/particpant-email.html
THese were in another branch that had not been merged or pushed - so have included them in this into main
=> changes in another branch that was not merged

app/views/macros/defaults.njk, app/views/sprint-17/teacher-or-mentors/cip-validation/finish-ect.html, app/views/sprint-17/teacher-or-mentors/cip-validation/particpant-email.html, app/views/sprint-17/teacher-or-mentors/cip-validation/pseudo-email-sign-in-ect.html
This will enable us to make the user research sessions a little more relative to the particular user we are doing the research with and their actual situation. School name etc.
=> added in macro defaults for user research

app/views/sprint-18/schools/participants.html, app/views/sprint-18/schools/participants/add/check-your-answers.html, app/views/sprint-18/schools/participants/add/choose-mentor.html, app/views/sprint-18/schools/participants/add/confirmation.html, app/views/sprint-18/schools/participants/add/email-address.html, app/views/sprint-18/schools/participants/add/name.html, app/views/sprint-18/schools/participants/details.html, app/views/sprint-18/schools/what-each-person-does.html
Ticket is here: https://dfedigital.atlassian.net/browse/CPDRP-684?atlOrigin=eyJpIjoiMDQ1YTkzODAyNGQ5NDQ1ZjhmYTZmYWZmNzhiNTM4YzkiLCJwIjoiaiJ9
=> Content for add participants

app/views/sprint-18/schools/participants.html, app/views/sprint-18/schools/what-each-person-does.html
Part of ticket https://dfedigital.atlassian.net/browse/CPDRP-684?atlOrigin=eyJpIjoiZjM0MzY3OTgzNWE1NDc2M2I4ZTZiODRkZjczMTU1YjQiLCJwIjoiaiJ9.
=> New header content with more explanation

app/views/index.html, app/views/sprint-18/step-by-step.html
Initial page build and content
=> Step by step

app/views/sprint-19/step-by-step.html
Iteration for this ticket: https://dfedigital.atlassian.net/browse/CPDRP-839?atlOrigin=eyJpIjoiMjUxYTgyMTZhZDRmNDdkYzlhMTk2ZmJhY2I3YTMzNzAiLCJwIjoiaiJ9
=> Step by step content update

app/views/admin/listings.html, app/views/sprint-19/schools/choose-induction-programme.html
Changed to the CIP only journey if a school is not eligible
=> Non eligible journey

app/views/macros/defaults.njk, app/views/sprint-20/check-your-email.html, app/views/sprint-20/emails/link-to-sign-in.html, app/views/sprint-20/how-to-get-an-account.html, app/views/sprint-20/index.html, app/views/sprint-20/nominations/confirm.html, app/views/sprint-20/nominations/confirmation.html, app/views/sprint-20/nominations/find-school.html, app/views/sprint-20/nominations/local-authority.html, app/views/sprint-20/nominations/resend-email.html, app/views/sprint-20/schools/expired-link.html, app/views/sprint-20/sign-in.html, app/views/sprint-20/signed-in.html
See https://dfedigital.atlassian.net/browse/CPDRP-815?atlOrigin=eyJpIjoiMmQyOWMwMGE3YzAzNDk2Mjk1YTZlYjI4ZTQ4M2VhMDUiLCJwIjoiaiJ9 for details.
=> Sign-in journey content updates

app/views/sprint-20/how-to-get-an-account.html, app/views/sprint-20/index.html, app/views/sprint-20/schools/participants/register/what-is-your-teacher-reference-number.html, app/views/sprint-20/sign-in.html
See this ticket for opt back in changes: https://dfedigital.atlassian.net/browse/CPDRP-906?atlOrigin=eyJpIjoiNmRjZWE4MDg5Y2ZhNDNlOWFhMDNlYmYxNjYwZjAwOGQiLCJwIjoiaiJ9
See this ticket for updates to the TRN page: https://dfedigital.atlassian.net/browse/CPDRP-915?atlOrigin=eyJpIjoiOTc4OTYzN2Y3NzlhNDVhNzkzMzI2NjkxOWQ1YzAyNDQiLCJwIjoiaiJ9
=> Opt back in and TRN page content updates

app/views/sprint-20/schools/manage-your-training.html, app/views/sprint-20/schools/participants/register/get-teacher-reference-number.html, app/views/sprint-20/schools/programme-choice.html
Content updates for this ticket: https://dfedigital.atlassian.net/browse/CPDRP-906?atlOrigin=eyJpIjoiODhhZDQzMmIyYTdmNDE3YmE4NGMzNmM3ZmU4NDAyYmUiLCJwIjoiaiJ9
=> Change DIY programme

app/views/sprint-20/schools/participants/register/get-teacher-reference-number.html, app/views/sprint-20/schools/participants/register/what-is-your-teacher-reference-number.html
https://dfedigital.atlassian.net/browse/CPDRP-915?atlOrigin=eyJpIjoiMjVlNmZkNmIyZWUxNGY0YmJkYTJmOTM3YjhiNzU1YTUiLCJwIjoiaiJ9
=> Guidance update for get a TRN reminder, and get a new TRN

app/views/sprint-21/schools/participants/add/check-your-answers.html, app/views/sprint-21/schools/participants/add/confirmation.html
Updates made based on testing feedback and design discussion. The ticket is https://dfedigital.atlassian.net/browse/CPDRP-826?atlOrigin=eyJpIjoiZjViMWIxMGRlMjBmNGNjOGE5MjY5NTI4Mzk1YmY3YjQiLCJwIjoiaiJ9.
=> 826 content check

app/views/admin/listings.html, app/views/index.html, app/views/latest/schools/confirmation.html, app/views/latest/schools/expect-early-career-teachers.html, app/views/latest/schools/nominate-induction-tutor.html, app/views/latest/schools/nominate-induction-tutor/check-your-answers.html, app/views/latest/schools/nominate-induction-tutor/confirmation.html, app/views/latest/schools/nominate-induction-tutor/email-address.html, app/views/latest/schools/nominate-induction-tutor/full-name.html, app/views/latest/schools/who-do-you-want-to-nominate.html
Work done around the nominate SIT journey - content review and design clean up.
=> 817 nominate sit

app/views/latest/schools/participants/add/check-your-answers.html, app/views/latest/schools/participants/add/confirmation.html, app/views/latest/schools/participants/add/email-address.html, app/views/latest/schools/participants/add/name.html, app/views/latest/schools/participants/details.html, app/views/latest/schools/participants/index.html
Further changes to this - to include option for 2 pariticpants during testing or general use
=> Participant dashboard

app/views/latest/schools/participants/add/email-address.html, app/views/latest/schools/participants/add/name.html, app/views/latest/schools/participants/details.html
Put logic in place to allow us to add more than 1 ECT into the prototype and still be able to change their details out etc.
=> added logic for the details page to change info if needed

app/views/latest/how-to-get-an-account.html
Have updated the text on this page (Kate already checked) @etheya please can you make sure the link for Register for your ...training is correct please :)
=> Updated How to access this page

app/views/latest/schools/training-programme/success.html
=> fixed typo - mange to manage

app/views/latest/schools/participants/what-each-person-does.html
Following UR, I've worked with the policy team to make these updates: https://docs.google.com/document/d/1_kWIHKm_ho8d85VA7sbYQeZ-J9W-EBMXUSbCzGwO1XI/edit#
This PR updates the prototype.
=> SIT as mentor guidance updated

app/views/includes/break.html, app/views/index.html
quick tidy up of some of the code on the main landing page.
=> landing page

app/assets/javascripts/auto-store-data.js, app/assets/javascripts/step-by-step-nav.js, app/data/session-data-defaults.js, app/filters.js, app/utils/filters-with-app-context.js, app/utils/wizard-helpers.js, lib/core_filters.js, lib/utils.js, listen-on-port.js, server.js, start.js
Run `npx standard --fix` to fix linting across the project
=> Lint javascript

app/views/layout.html, app/views/schools/training-programme/index.html, app/views/sign-in.html, lib/filters-with-app-context.js, server.js
- Enable decorateFormAttributes filter
- Log session data
- Add 2 examples of decorateFormAttributes
=> Add examples of decorateFormAttributes

app/views/schools/participants/register/date-of-birth.html, app/views/teacher-or-mentors/cip-validation/qct-ect.html
Chanhed the current date example out with one that fits with the GDS pattern guidelines
=> changed pattern numbers

app/views/nominations/confirmation.html, app/views/nominations/email-already-in-use.html, app/views/nominations/expect-early-career-teachers.html, app/views/nominations/expired-link.html, app/views/nominations/find-school.html, app/views/nominations/local-authority.html, app/views/nominations/resend-email.html, app/views/nominations/success.html
added in the new decorate functionality
=> code clean up of this section

app/views/cannot-use-this-service.html, app/views/check-your-email.html, app/views/guidance_1.html, app/views/how-to-get-an-account.html, app/views/nominations/confirm.html, app/views/schools/DWN-dyo-cohort-nextsteps-noect.html, app/views/schools/confirm-choice.html, app/views/schools/induction-tutor-already-nominated.html, app/views/schools/materials/which.html, app/views/schools/participants/add/existing-mentor.html, app/views/schools/participants/add/which-mentor.html, app/views/schools/participants/induction-tutor/email-address.html, app/views/schools/participants/induction-tutor/full-name.html, app/views/schools/participants/register/confirm-name.html, app/views/schools/participants/register/name.html, app/views/schools/participants/register/national-insurance-number.html, app/views/schools/participants/register/teacher-reference-number.html, app/views/schools/programme-choice.html, app/views/schools/report/incorrect-signup.html, app/views/schools/sign-up-to-training-provider.html, app/views/signed-in.html
further page cleanup using the decorate code
=> decorate code clean up

app/views/admin/preload.html, app/views/schools/participants/index.html
preload option to show withdrawn
=> additions to preload

app/data/session-data-defaults.js
Cleared users information -  security
=> removed users details from ur session

app/data/session-data-defaults.js, app/views/schools/participants/index.html
=> ur session 3 nov 22

app/data/session-data-defaults.js, app/views/schools/participants/index.html
fixed spacing and corrected name of school
=> Ur session 3

app/data/session-data-defaults.js
=> users info

app/views/schools/participants/details.html
that the SIT may want to delete that are validated.
=> change of content for FIP particpants

app/views/schools/participants/add/check-your-answers.html, app/views/schools/participants/add/start-date.html, app/views/schools/participants/details.html, app/views/schools/participants/index.html
small change to test what users have been saying about induction programme - not training programme
=> induction programme wording for testing

app/views/schools/participants/index.html
| Before | After |
|--|--|
| ![ecf-prototype-pr-212 herokuapp com_schools_participants__cohort=2021](https://user-images.githubusercontent.com/319055/143591735-f5d82e6b-3635-47a0-a60e-c340c6eb4971.png) | ![localhost_3001_schools_participants_](https://user-images.githubusercontent.com/319055/143591742-4620db5f-9981-4153-a5df-82d81d1d4678.png) |
=> Improve line lengths on participant pages

app/data/session-data-defaults.js, app/routes.js, app/views/admin/user-research/participant-start.html, lib/filters-with-app-context.js
- Add form for setting names
- Use env variables to set names, email, lead provider and delivery partner
- Derive first name and emails from full name
SCHOOL_NAME
FULL_NAME
DELIVERY_PARTNER
LEAD_PROVIDER
=> Allow setting of defaults using env vars or a form

.gitignore, app/views/admin/listings.html, app/views/admin/preload.html, app/views/schools/participants/register/cannot-find-your-details.html, app/views/schools/participants/register/confirmation.html, app/views/schools/participants/register/date-of-birth.html, app/views/schools/participants/register/name.html, app/views/schools/participants/register/national-insurance-number.html
Moved some stuff into conditionals - but also put in better order and simplified validation rules slightly.
=> clean up of preload page

app/data/session-data-defaults.js
Not working via Heroku so adding here just in case.
=> ur defaults

app/data/session-data-defaults.js, app/views/admin/preload.html, app/views/schools/participants/add/check-your-answers.html, app/views/schools/participants/add/confirmation.html, app/views/schools/participants/add/date-of-birth.html, app/views/schools/participants/add/email-address.html, app/views/schools/participants/add/have-trn.html, app/views/schools/participants/add/name.html, app/views/schools/participants/add/start-date.html, app/views/schools/participants/add/teacher-reference-number.html, app/views/schools/participants/add/transfer/check-your-answers.html, app/views/schools/participants/add/transfer/confirmation.html, app/views/schools/participants/add/transfer/email-address.html, app/views/schools/participants/add/transfer/index.html, app/views/schools/participants/add/transfer/moving-from-another-school.html, app/views/schools/participants/add/transfer/start-date.html, app/views/schools/participants/add/who-do-you-want-to-add.html, app/views/schools/participants/details.html, app/views/schools/participants/index.html, app/views/schools/participants/register/confirmation.html, app/views/schools/participants/register/teacher-reference-number.html, app/views/schools/participants/transfer/confirmation.html
=> 257 refine

app/data/session-data-defaults.js, app/routes.js, app/routes/participants.js, app/views/participants/details.html, app/views/participants/index.html
A proof of concept showing how to add and edit multiple participants
=> Example of code allowing multiple participants

app/data/session-data-defaults.js, app/routes/participants.js, app/views/schools/participants/details.html
Checked to make sure the status information was coming through correctly with the new ID structure.
=> link up with details and remove

app/views/schools/manage-your-training.html
=> manage training page change for when someone has told us about next year

app/views/schools/sign-up-to-training-provider.html, app/views/schools/training-programme/how-will-you-run.html, app/views/schools/training-programme/same.html, app/views/schools/training-programme/success.html
Correct guidance links and target code
=> 469 guidance

app/routes/participants.js, app/views/includes/summary_induction_date.html, app/views/includes/summary_induction_start.html, app/views/schools/participants/add/check-your-answers.html, app/views/schools/participants/add/email-address.html, app/views/schools/participants/add/induction-start-date.html, app/views/schools/participants/add/start-date.html
New page to assist with the Appropriate Bodies work we will be doing. To capture the induction start date for the ECT. This also includes changes to the CYA page with a new row added.
Also induction start date should not be asked to mentors.
=> Induction start

app/views/schools/manage-your-training.html
Updated the copy on the Manage your training page under New ECTs starting this year.
=> content update
